package org.vedruna.model.enums;

public enum Country {
    AF, //("Afganistán"),
    AL, //("Albania"),
    DZ, //("Argelia"),
    AD, //("Andorra"),
    AO, //("Angola"),
    AG, //("Antigua y Barbuda"),
    AR, //("Argentina"),
    AM, //("Armenia"),
    AU, //("Australia"),
    AT, //("Austria"),
    AZ, //("Azerbaiyán"),
    BS, //("Bahamas"),
    BH, //("Bahrein"),
    BD, //("Bangladesh"),
    BB, //("Barbados"),
    BY, //("Belarús"),
    BE, //("Bélgica"),
    BZ, //("Belice"),
    BJ, //("Benin"),
    BT, //("Bhután"),
    BO, //("Bolivia"),
    BA, //("Bosnia y Herzegovina"),
    BW, //("Botswana"),
    BR, //("Brasil"),
    BN, //("Brunei Darussalam"),
    BG, //("Bulgaria"),
    BF, //("Burkina Faso"),
    BI, //("Burundi"),
    CV, //("Cabo Verde"),
    KH, //("Camboya"),
    CM, //("Camerún"),
    CA, //("Canadá"),
    CF, //("República Centroafricana"),
    TD, //("Chad"),
    CL, //("Chile"),
    CN, //("China"),
    CO, //("Colombia"),
    KM, //("Comoras"),
    CG, //("Congo"),
    CR, //("Costa Rica"),
    CI, //("Côte d’Ivoire"),
    HR, //("Croacia"),
    CU, //("Cuba"),
    CY, //("Chipre"),
    CZ, //("Chequia"),
    KP, //("República Popular Democrática de Corea"),
    CD, //("República Democrática del Congo"),
    DK, //("Dinamarca"),
    DJ, //("Djibouti"),
    DM, //("Dominica"),
    DO, //("República Dominicana"),
    EC, //("Ecuador"),
    EG, //("Egipto"),
    SV, //("El Salvador"),
    GQ, //("Guinea Ecuatorial"),
    ER, //("Eritrea"),
    EE, //("Estonia"),
    SZ, //("Eswatini"),
    ET, //("Etiopía"),
    FJ, //("Fiji"),
    FI, //("Finlandia"),
    FR, //("Francia"),
    GA, //("Gabón"),
    GM, //("Gambia"),
    GE, //("Georgia"),
    DE, //("Alemania"),
    GH, //("Ghana"),
    GR, //("Grecia"),
    GD, //("Granada"),
    GT, //("Guatemala"),
    GN, //("Guinea"),
    GW, //("Guinea-Bissau"),
    GY, //("Guyana"),
    HT, //("Haití"),
    HN, //("Honduras"),
    HU, //("Hungría"),
    IS, //("Islandia"),
    IN, //("India"),
    ID, //("Indonesia"),
    IR, //("Irán"),
    IQ, //("Iraq"),
    IE, //("Irlanda"),
    IL, //("Israel"),
    IT, //("Italia"),
    JM, //("Jamaica"),
    JP, //("Japón"),
    JO, //("Jordania"),
    KZ, //("Kazajstán"),
    KE, //("Kenya"),
    KI, //("Kiribati"),
    KW, //("Kuwait"),
    KG, //("Kirguistán"),
    LA, //("República Democrática Popular Lao"),
    LV, //("Letonia"),
    LB, //("Líbano"),
    LS, //("Lesotho"),
    LR, //("Liberia"),
    LY, //("Libia"),
    LI, //("Liechtenstein"),
    LT, //("Lituania"),
    LU, //("Luxemburgo"),
    MG, //("Madagascar"),
    MW, //("Malawi"),
    MY, //("Malasia"),
    MV, //("Maldivas"),
    ML, //("Malí"),
    MT, //("Malta"),
    MH, //("Islas Marshall"),
    MR, //("Mauritania"),
    MU, //("Mauricio"),
    MX, //("México"),
    FM, //("Micronesia"),
    MC, //("Mónaco"),
    MN, //("Mongolia"),
    ME, //("Montenegro"),
    MA, //("Marruecos"),
    MZ, //("Mozambique"),
    MM, //("Myanmar"),
    NA, //("Namibia"),
    NR, //("Nauru"),
    NP, //("Nepal"),
    NL, //("Países Bajos"),
    NZ, //("Nueva Zelandia"),
    NI, //("Nicaragua"),
    NE, //("Níger"),
    NG, //("Nigeria"),
    MK, //("Macedonia del Norte"),
    NO, //("Noruega"),
    OM, //("Omán"),
    PK, //("Pakistán"),
    PW, //("Palau"),
    PA, //("Panamá"),
    PG, //("Papua Nueva Guinea"),
    PY, //("Paraguay"),
    PE, //("Perú"),
    PH, //("Filipinas"),
    PL, //("Polonia"),
    PT, //("Portugal"),
    QA, //("Qatar"),
    KR, //("República de Corea"),
    MD, //("República de Moldova"),
    RO, //("Rumanía"),
    RU, //("Federación de Rusia"),
    RW, //("Rwanda"),
    KN, //("Saint Kitts y Nevis"),
    LC, //("Santa Lucía"),
    VC, //("San Vicente y las Granadinas"),
    WS, //("Samoa"),
    SM, //("San Marino"),
    ST, //("Santo Tomé y Príncipe"),
    SA, //("Arabia Saudita"),
    SN, //("Senegal"),
    RS, //("Serbia"),
    SC, //("Seychelles"),
    SL, //("Sierra Leona"),
    SG, //("Singapur"),
    SK, //("Eslovaquia"),
    SI, //("Eslovenia"),
    SB, //("Islas Salomón"),
    SO, //("Somalia"),
    ZA, //("Sudáfrica"),
    SS, //("Sudán del Sur"),
    ES, //("España"),
    LK, //("Sri Lanka"),
    SD, //("Sudán"),
    SR, //("Suriname"),
    SE, //("Suecia"),
    CH, //("Suiza"),
    SY, //("República Árabe Siria"),
    TJ, //("Tayikistán"),
    TH, //("Tailandia"),
    TL, //("Timor-Leste"),
    TG, //("Togo"),
    TO, //("Tonga"),
    TT, //("Trinidad y Tabago"),
    TN, //("Túnez"),
    TR, //("Türkiye"),
    TM, //("Turkmenistán"),
    TV, //("Tuvalu"),
    UG, //("Uganda"),
    UA, //("Ucrania"),
    AE, //("Emiratos Árabes Unidos"),
    GB, //("Reino Unido de Gran Bretaña e Irlanda del Norte"),
    TZ, //("República Unida de Tanzanía"),
    US, //("Estados Unidos de América"),
    UY, //("Uruguay"),
    UZ, //("Uzbekistán"),
    VU, //("Vanuatu"),
    VE, //("Venezuela"),
    VN, //("Viet Nam"),
    YE, //("Yemen"),
    ZM, //("Zambia"),
    ZW, //("Zimbabwe"),
    VA, //("Santa Sede"),
    PS //("Estado de Palestina")
}

